name: neo_pokedex
description: "A Pokedex app made with Flutter using the PokeAPI in GraphQL."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  graphql_flutter: ^5.0.0
  audioplayers: ^6.1.0
  logging: ^1.3.0
  flutter_svg: ^2.0.12
  http: 1.2.2
  shared_preferences: 2.3.3
  auto_route: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/animations/
  uses-material-design: true
