name: neo_pokedex
description: "A Pokedex app made with Flutter using the PokeAPI in GraphQL."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  graphql_flutter: ^5.0.0
  audioplayers: ^6.1.0
  logging: ^1.3.0
  flutter_svg: ^2.0.16
  http: 1.2.2
  shared_preferences: 2.3.3
  auto_route: ^9.2.2
  logger: ^2.5.0
  share_plus: ^10.1.2
  screenshot: ^3.0.0
  path_provider: ^2.1.5

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/icon.png"

dev_dependencies:
  flutter_launcher_icons: "^0.14.1"
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/animations/
  uses-material-design: true
